### ISSUE TITLE
Veeam v10 is not supported

### ISSUE THREAD

**Issue by lenaertswouter** [exospheredata/veeam#7]
First of all, LOVING your work on this project!

The issue:
By specifying a specific URL for the ISO we can make this code compatible with newer versions of Veeam like the 9.5 4b update. With the new Veeam version 10 however this does not work because it requires a higher version of .net

The code installs .net 4.5.2
v10 requires .net 4.7.2

The file "resources/prerequisites.rb" uses the .net installation file found on the Veeam iso called "NDP452-KB2901907-x86-x64-AllOS-ENU.exe"
On v10 however this installation file is called  "NDP472-KB4054530-x86-x64-AllOS-ENU.exe"

**Comment by lenaertswouter** [comment]
Would it be an idea to add 2 attributes that allows us to specify the .net version and the path to the installer?

**Comment by goodrum** [comment]
@lenaertswouter,

Thank you for taking the time to give this great feedback.  We appreciate any opportunity to hear positive or negative reactions to the project.  

It is entirely possible that swapping out the .NET component to be an attribute will work.  My understanding is that the v10 install procedure has changed slightly so this might not be a single fix to add the support.  

We will need to do a few tests to see the best approach.  I am curious if you have tested pre-installing the correct .NET version and then running the full cookbook installation.  Does this work?

**Comment by lenaertswouter** [comment]
@goodrum 
Ok so I did as you suggested and it seems you are right about it not being a single fix. The parameters that we have to pass to the msi that installs B&R seem to have changed so it crashes at the installation.

**Comment by goodrum** [comment]
@lenaertswouter,

Well, that is unfortunate.  I will try to see if I can get some time to take a look at the changes to see what is required to update the version support.  Alternately, we are more than happy to review a PR if you are so inclined.

**Comment by goodrum** [comment]
@lenaertswouter,

I spent the weekend looking into the requirements to support v10.  The good news is that I have been able to successfully upgrade the code to support v10 installation.  I still need to do some testing and validation and ensure that I haven't introduced any regressions.  I had to upgrade all the components to support Chef Client 16 so I will also need to run a few tests against previous versions.  I haven't been able to test the Proxy, Explorers, and Host registration code.  

The big changes seem to only be in the DotNet versions and SQL Express installations.  Once I made the necessary changes in the prerequisites, the rest of the installation process worked just fine.

More details to come.

**Comment by lenaertswouter** [comment]
Is there any way I can assist in testing the Proxy, Explorers, and Host registration code? I did not see any additional branch however.

**Comment by goodrum** [comment]
@lenaertswouter and @MichaelCade 

I have pushed the branch `feature/veeam_10.0.0.4461_support` to the repository with all the upgrades and changes to support v10 installation.  I still need to test the Proxy and Host registration code.  If you are willing to test the code for me, then I would appreciate the help.

**Comment by lenaertswouter** [comment]
Ok this morning I finally found some time to do some testing. One bug I ran into is when I use the "veeam_host" resource in the following way:
`veeam_host 'localhost' do
  vbr_server      'localhost'
  vbr_username    '.\\administrator'
  vbr_password    'Ditiseentest12#$'
  host_username  '.\\administrator'
  host_password  'Ditiseentest12#$'
  host_type      'windows'
  action :add
end`

The problem seems to be related that in line 86 you pass the "-Port" argument. However, according to the Veeam documentation the powershell commandlet "Add-VBRHvHost" does not support that parameter.
**Source:** https://helpcenter.veeam.com/docs/backup/powershell/add-vbrhvhost.html?ver=100

**Comment by goodrum** [comment]
@lenaertswouter , ok this is good feedback.  The HvHost items were not fully tested but I see exactly what you are saying.  I made a small adjustment to move that bit of code into the ESX items only.  I just pushed the commit.

**Comment by lenaertswouter** [comment]
Perfect, that last update seems to have solved it!
Another issue I ran into has to do that the veeam_host resource crashes on passwords that contain uncommon ")(" characters. Some test-kitchen environments create these long passwords with many types of characters.  I think this is because on line 68 the password in inserted into the PowerShell code without quotations "". 

So instead of
`-Password #{new_resource.vbr_password} ``

Should it be somthing like?
`-Password "#{new_resource.vbr_password}" ``

On the other hand this issue does not seem related to v10 and should perhaps be treated as a separate case. But that is your call.

**Comment by goodrum** [comment]
@lenaertswouter , you mean not everyone uses Password123 :) 

Good catch and easy update.  I just pushed the change.  I appreciate the continued testing and validation.  Let me know if this works and I will plan to finalize and publish the release.

**Comment by lenaertswouter** [comment]
LOL :P
I too appreciate your quick response. With these changes and some more coming up in some more pull requests the organization I work for will be able to use in in production in many locations.
Just finished all the tests I wanted to run. We can confirm both the veeam_host and veeam_proxy resources seem to work fine. I was able to create and delete them successfully. As far as I care, after we publish this issue can be closed.

**Comment by goodrum** [comment]
@lenaertswouter, Wonderful news.  Sounds like we are pretty much there.  I will work to wrap this up and push the release in the next day or so.  

I look forward to reviewing the upcoming PRs.  Thanks for joining and helping the community

**Comment by goodrum** [comment]
It took a bit but the new release is finally out with support for versions 9.5.4b, 10.0 and 10.0a included.  Thank you for your contributions and feedback - @lenaertswouter, @horori, @anorstrom
