### ISSUE TITLE
Support for 9.5 Update 4b

### ISSUE THREAD

**Issue by anorstrom** [exospheredata/veeam#9]
Hi,

Would it be possible to add support for installation of 9.5 Update 4b to this cookbook?

Thanks,
Andreas

**Comment by goodrum** [comment]
@anorstrom , we are working on a new release as time permits to bring the entire code-line to date and include v10.  I will see if we can slip this update into the code as well.

**Comment by anorstrom** [comment]
Nice, thank you @goodrum  

Some work on Update 4b has been done in this fork https://github.com/horori/veeam/commits/master. I tested that fork and it seems to work. Update 4b gets installed. Some things still should be adjusted I think, like the name of the SQL instance, which still include something like VEEAMSQL2012.

**Comment by lenaertswouter** [comment]
I am working on that fork to see if I can make a PR that integrates Horori's code into your v10 branch

**Comment by lenaertswouter** [comment]
We where also thinking on making a PR that allows the SQL instance to be more generic or configurable by an attribute.

**Comment by lenaertswouter** [comment]
Started working on it here:
https://github.com/exospheredata/veeam/compare/feature/veeam_10.0.0.4461_support...lenaertswouter:Add9.5.4bSupport

**Comment by lenaertswouter** [comment]
PR has been created

**Comment by goodrum** [comment]
@anorstrom, I have merged the PR from @lenaertswouter into the new v10 branch.  I plan to wrap up the branch very soon and merge into master with a new release in the supermarket.  I will close this Issue out and thank you for raising the request.
